<SplashScreen>:
    canvas.before:
        Color:
            rgba: 0,0,0,1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size

    anim_box: anim_box
    AnchorLayout:
        id: anim_box

<AnimWidget@Widget>:
    canvas:
        Color:
            rgba: 0.7, 0.3, 0.9, 1
        Rectangle:
            pos: self.pos
            size: self.size
    size_hint: None, None
    size: 400, 30